//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.03 at 10:41:25 PM CST 
//


package epc.epcsalesapi.soap.wsclient.updateTmpReservePickupLoc;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for invUpdateTmpReservePickupLocBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invUpdateTmpReservePickupLocBean"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="orderChannel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tmpReserveID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="pickupStoreCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="apiUserId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="createChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invUpdateTmpReservePickupLocBean", propOrder = {
    "orderChannel",
    "tmpReserveID",
    "pickupStoreCode",
    "userID",
    "apiUserId",
    "createChannel"
})
public class InvUpdateTmpReservePickupLocBean {

    @XmlElement(required = true)
    protected String orderChannel;
    protected int tmpReserveID;
    @XmlElement(required = true)
    protected String pickupStoreCode;
    protected int userID;
    protected String apiUserId;
    protected String createChannel;

    /**
     * Gets the value of the orderChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderChannel() {
        return orderChannel;
    }

    /**
     * Sets the value of the orderChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderChannel(String value) {
        this.orderChannel = value;
    }

    /**
     * Gets the value of the tmpReserveID property.
     * 
     */
    public int getTmpReserveID() {
        return tmpReserveID;
    }

    /**
     * Sets the value of the tmpReserveID property.
     * 
     */
    public void setTmpReserveID(int value) {
        this.tmpReserveID = value;
    }

    /**
     * Gets the value of the pickupStoreCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupStoreCode() {
        return pickupStoreCode;
    }

    /**
     * Sets the value of the pickupStoreCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupStoreCode(String value) {
        this.pickupStoreCode = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     */
    public int getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     */
    public void setUserID(int value) {
        this.userID = value;
    }

    /**
     * Gets the value of the apiUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApiUserId() {
        return apiUserId;
    }

    /**
     * Sets the value of the apiUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApiUserId(String value) {
        this.apiUserId = value;
    }

    /**
     * Gets the value of the createChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateChannel() {
        return createChannel;
    }

    /**
     * Sets the value of the createChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateChannel(String value) {
        this.createChannel = value;
    }

}
