//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.03 at 10:41:25 PM CST 
//


package epc.epcsalesapi.soap.wsclient.updateTmpReservePickupLoc;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.smc.testSpringboot3ConsumeSoap.wsclient.updateTmpReservePickupLoc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UpdateTmpReservePickupLocEpc_QNAME = new QName("http://online_store.pos/", "UpdateTmpReservePickupLocEpc");
    private final static QName _UpdateTmpReservePickupLocEpcResponse_QNAME = new QName("http://online_store.pos/", "UpdateTmpReservePickupLocEpcResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.smc.testSpringboot3ConsumeSoap.wsclient.updateTmpReservePickupLoc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateTmpReservePickupLocEpc }
     * 
     */
    public UpdateTmpReservePickupLocEpc createUpdateTmpReservePickupLocEpc() {
        return new UpdateTmpReservePickupLocEpc();
    }

    /**
     * Create an instance of {@link UpdateTmpReservePickupLocEpcResponse }
     * 
     */
    public UpdateTmpReservePickupLocEpcResponse createUpdateTmpReservePickupLocEpcResponse() {
        return new UpdateTmpReservePickupLocEpcResponse();
    }

    /**
     * Create an instance of {@link InvUpdateTmpReservePickupLocBean }
     * 
     */
    public InvUpdateTmpReservePickupLocBean createInvUpdateTmpReservePickupLocBean() {
        return new InvUpdateTmpReservePickupLocBean();
    }

    /**
     * Create an instance of {@link InvUpdateTmpReservePickupLocResultBean }
     * 
     */
    public InvUpdateTmpReservePickupLocResultBean createInvUpdateTmpReservePickupLocResultBean() {
        return new InvUpdateTmpReservePickupLocResultBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateTmpReservePickupLocEpc }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateTmpReservePickupLocEpc }{@code >}
     */
//    @XmlElementDecl(namespace = "http://online_store.pos/", name = "UpdateTmpReservePickupLocEpc")
//    public JAXBElement<UpdateTmpReservePickupLocEpc> createUpdateTmpReservePickupLocEpc(UpdateTmpReservePickupLocEpc value) {
//        return new JAXBElement<UpdateTmpReservePickupLocEpc>(_UpdateTmpReservePickupLocEpc_QNAME, UpdateTmpReservePickupLocEpc.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateTmpReservePickupLocEpcResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateTmpReservePickupLocEpcResponse }{@code >}
     */
//    @XmlElementDecl(namespace = "http://online_store.pos/", name = "UpdateTmpReservePickupLocEpcResponse")
//    public JAXBElement<UpdateTmpReservePickupLocEpcResponse> createUpdateTmpReservePickupLocEpcResponse(UpdateTmpReservePickupLocEpcResponse value) {
//        return new JAXBElement<UpdateTmpReservePickupLocEpcResponse>(_UpdateTmpReservePickupLocEpcResponse_QNAME, UpdateTmpReservePickupLocEpcResponse.class, null, value);
//    }

}
