//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.03 at 10:36:15 PM CST 
//


package epc.epcsalesapi.soap.wsclient.extendTmpReserve;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtendTmpReserveResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtendTmpReserveResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InvExtendTmpReserveResultBean" type="{http://online_store.pos/}invExtendTmpReserveResultBean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "ExtendTmpReserveResponse")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendTmpReserveResponse", propOrder = {
    "invExtendTmpReserveResultBean"
})
public class ExtendTmpReserveResponse {

    @XmlElement(name = "InvExtendTmpReserveResultBean")
    protected InvExtendTmpReserveResultBean invExtendTmpReserveResultBean;

    /**
     * Gets the value of the invExtendTmpReserveResultBean property.
     * 
     * @return
     *     possible object is
     *     {@link InvExtendTmpReserveResultBean }
     *     
     */
    public InvExtendTmpReserveResultBean getInvExtendTmpReserveResultBean() {
        return invExtendTmpReserveResultBean;
    }

    /**
     * Sets the value of the invExtendTmpReserveResultBean property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvExtendTmpReserveResultBean }
     *     
     */
    public void setInvExtendTmpReserveResultBean(InvExtendTmpReserveResultBean value) {
        this.invExtendTmpReserveResultBean = value;
    }

}
