//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.03 at 10:36:15 PM CST 
//


package epc.epcsalesapi.soap.wsclient.extendTmpReserve;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for invExtendTmpReserveBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invExtendTmpReserveBean"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tmpReserveID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="extendReserveMins" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invExtendTmpReserveBean", propOrder = {
    "tmpReserveID",
    "extendReserveMins",
    "userID"
})
public class InvExtendTmpReserveBean {

    protected int tmpReserveID;
    protected int extendReserveMins;
    protected int userID;

    /**
     * Gets the value of the tmpReserveID property.
     * 
     */
    public int getTmpReserveID() {
        return tmpReserveID;
    }

    /**
     * Sets the value of the tmpReserveID property.
     * 
     */
    public void setTmpReserveID(int value) {
        this.tmpReserveID = value;
    }

    /**
     * Gets the value of the extendReserveMins property.
     * 
     */
    public int getExtendReserveMins() {
        return extendReserveMins;
    }

    /**
     * Sets the value of the extendReserveMins property.
     * 
     */
    public void setExtendReserveMins(int value) {
        this.extendReserveMins = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     */
    public int getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     */
    public void setUserID(int value) {
        this.userID = value;
    }

}
