//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.03 at 10:36:15 PM CST 
//


package epc.epcsalesapi.soap.wsclient.extendTmpReserve;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.smc.testSpringboot3ConsumeSoap.wsclient.extendTmpReserve package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExtendTmpReserve_QNAME = new QName("http://online_store.pos/", "ExtendTmpReserve");
    private final static QName _ExtendTmpReserveResponse_QNAME = new QName("http://online_store.pos/", "ExtendTmpReserveResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.smc.testSpringboot3ConsumeSoap.wsclient.extendTmpReserve
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExtendTmpReserve }
     * 
     */
    public ExtendTmpReserve createExtendTmpReserve() {
        return new ExtendTmpReserve();
    }

    /**
     * Create an instance of {@link ExtendTmpReserveResponse }
     * 
     */
    public ExtendTmpReserveResponse createExtendTmpReserveResponse() {
        return new ExtendTmpReserveResponse();
    }

    /**
     * Create an instance of {@link InvExtendTmpReserveBean }
     * 
     */
    public InvExtendTmpReserveBean createInvExtendTmpReserveBean() {
        return new InvExtendTmpReserveBean();
    }

    /**
     * Create an instance of {@link InvExtendTmpReserveResultBean }
     * 
     */
    public InvExtendTmpReserveResultBean createInvExtendTmpReserveResultBean() {
        return new InvExtendTmpReserveResultBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendTmpReserve }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExtendTmpReserve }{@code >}
     */
//    @XmlElementDecl(namespace = "http://online_store.pos/", name = "ExtendTmpReserve")
//    public JAXBElement<ExtendTmpReserve> createExtendTmpReserve(ExtendTmpReserve value) {
//        return new JAXBElement<ExtendTmpReserve>(_ExtendTmpReserve_QNAME, ExtendTmpReserve.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendTmpReserveResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExtendTmpReserveResponse }{@code >}
     */
//    @XmlElementDecl(namespace = "http://online_store.pos/", name = "ExtendTmpReserveResponse")
//    public JAXBElement<ExtendTmpReserveResponse> createExtendTmpReserveResponse(ExtendTmpReserveResponse value) {
//        return new JAXBElement<ExtendTmpReserveResponse>(_ExtendTmpReserveResponse_QNAME, ExtendTmpReserveResponse.class, null, value);
//    }

}
