//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.03 at 10:25:29 PM CST 
//


package epc.epcsalesapi.soap.wsclient.cancelTmpReserve;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CancelTmpReserveResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CancelTmpReserveResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InvCancelTmpReserveResultBean" type="{http://online_store.pos/}invCancelTmpReserveResultBean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "CancelTmpReserveResponse")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancelTmpReserveResponse", propOrder = {
    "invCancelTmpReserveResultBean"
})
public class CancelTmpReserveResponse {

    @XmlElement(name = "InvCancelTmpReserveResultBean")
    protected InvCancelTmpReserveResultBean invCancelTmpReserveResultBean;

    /**
     * Gets the value of the invCancelTmpReserveResultBean property.
     * 
     * @return
     *     possible object is
     *     {@link InvCancelTmpReserveResultBean }
     *     
     */
    public InvCancelTmpReserveResultBean getInvCancelTmpReserveResultBean() {
        return invCancelTmpReserveResultBean;
    }

    /**
     * Sets the value of the invCancelTmpReserveResultBean property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvCancelTmpReserveResultBean }
     *     
     */
    public void setInvCancelTmpReserveResultBean(InvCancelTmpReserveResultBean value) {
        this.invCancelTmpReserveResultBean = value;
    }

}
