//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.03 at 10:25:29 PM CST 
//


package epc.epcsalesapi.soap.wsclient.cancelTmpReserve;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.smc.testSpringboot3ConsumeSoap.wsclient.cancelTmpReserve package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CancelTmpReserve_QNAME = new QName("http://online_store.pos/", "CancelTmpReserve");
    private final static QName _CancelTmpReserveResponse_QNAME = new QName("http://online_store.pos/", "CancelTmpReserveResponse");
    private final static QName _GetString_QNAME = new QName("http://online_store.pos/", "getString");
    private final static QName _GetStringResponse_QNAME = new QName("http://online_store.pos/", "getStringResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.smc.testSpringboot3ConsumeSoap.wsclient.cancelTmpReserve
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CancelTmpReserve }
     * 
     */
    public CancelTmpReserve createCancelTmpReserve() {
        return new CancelTmpReserve();
    }

    /**
     * Create an instance of {@link CancelTmpReserveResponse }
     * 
     */
    public CancelTmpReserveResponse createCancelTmpReserveResponse() {
        return new CancelTmpReserveResponse();
    }

    /**
     * Create an instance of {@link GetString }
     * 
     */
    public GetString createGetString() {
        return new GetString();
    }

    /**
     * Create an instance of {@link GetStringResponse }
     * 
     */
    public GetStringResponse createGetStringResponse() {
        return new GetStringResponse();
    }

    /**
     * Create an instance of {@link InvCancelTmpReserveBean }
     * 
     */
    public InvCancelTmpReserveBean createInvCancelTmpReserveBean() {
        return new InvCancelTmpReserveBean();
    }

    /**
     * Create an instance of {@link InvCancelTmpReserveResultBean }
     * 
     */
    public InvCancelTmpReserveResultBean createInvCancelTmpReserveResultBean() {
        return new InvCancelTmpReserveResultBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelTmpReserve }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CancelTmpReserve }{@code >}
     */
//    @XmlElementDecl(namespace = "http://online_store.pos/", name = "CancelTmpReserve")
//    public JAXBElement<CancelTmpReserve> createCancelTmpReserve(CancelTmpReserve value) {
//        return new JAXBElement<CancelTmpReserve>(_CancelTmpReserve_QNAME, CancelTmpReserve.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelTmpReserveResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CancelTmpReserveResponse }{@code >}
     */
//    @XmlElementDecl(namespace = "http://online_store.pos/", name = "CancelTmpReserveResponse")
//    public JAXBElement<CancelTmpReserveResponse> createCancelTmpReserveResponse(CancelTmpReserveResponse value) {
//        return new JAXBElement<CancelTmpReserveResponse>(_CancelTmpReserveResponse_QNAME, CancelTmpReserveResponse.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetString }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetString }{@code >}
     */
//    @XmlElementDecl(namespace = "http://online_store.pos/", name = "getString")
//    public JAXBElement<GetString> createGetString(GetString value) {
//        return new JAXBElement<GetString>(_GetString_QNAME, GetString.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStringResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetStringResponse }{@code >}
     */
//    @XmlElementDecl(namespace = "http://online_store.pos/", name = "getStringResponse")
//    public JAXBElement<GetStringResponse> createGetStringResponse(GetStringResponse value) {
//        return new JAXBElement<GetStringResponse>(_GetStringResponse_QNAME, GetStringResponse.class, null, value);
//    }

}
