//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.02 at 05:15:32 PM CST 
//


package epc.epcsalesapi.soap.wsclient.createTmpReserve;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for invCreateTmpReserveBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invCreateTmpReserveBean"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="orderChannel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="orderReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="productCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pickupStoreCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="reserveQty" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="reserveSerialNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="reserveMins" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="apiUserId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="createChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="isEpc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
//@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invCreateTmpReserveBean", propOrder = {
    "orderChannel",
    "orderReference",
    "productType",
    "productCode",
    "pickupStoreCode",
    "reserveQty",
    "reserveSerialNo",
    "reserveMins",
    "userID",
    "apiUserId",
    "createChannel",
    "isEpc"
})
public class InvCreateTmpReserveBean {

    @XmlElement(required = true)
    protected String orderChannel;
    @XmlElement(required = true, nillable = true)
    protected String orderReference;
    @XmlElement(required = true)
    protected String productType;
    @XmlElement(required = true)
    protected String productCode;
    @XmlElement(required = true)
    protected String pickupStoreCode;
    protected int reserveQty;
    @XmlElement(required = true)
    protected String reserveSerialNo;
    protected int reserveMins;
    @XmlElement(required = true)
    protected String userID;
    protected String apiUserId;
    protected String createChannel;
    protected String isEpc;

    /**
     * Gets the value of the orderChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderChannel() {
        return orderChannel;
    }

    /**
     * Sets the value of the orderChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderChannel(String value) {
        this.orderChannel = value;
    }

    /**
     * Gets the value of the orderReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderReference() {
        return orderReference;
    }

    /**
     * Sets the value of the orderReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderReference(String value) {
        this.orderReference = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the pickupStoreCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupStoreCode() {
        return pickupStoreCode;
    }

    /**
     * Sets the value of the pickupStoreCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupStoreCode(String value) {
        this.pickupStoreCode = value;
    }

    /**
     * Gets the value of the reserveQty property.
     * 
     */
    public int getReserveQty() {
        return reserveQty;
    }

    /**
     * Sets the value of the reserveQty property.
     * 
     */
    public void setReserveQty(int value) {
        this.reserveQty = value;
    }

    /**
     * Gets the value of the reserveSerialNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReserveSerialNo() {
        return reserveSerialNo;
    }

    /**
     * Sets the value of the reserveSerialNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReserveSerialNo(String value) {
        this.reserveSerialNo = value;
    }

    /**
     * Gets the value of the reserveMins property.
     * 
     */
    public int getReserveMins() {
        return reserveMins;
    }

    /**
     * Sets the value of the reserveMins property.
     * 
     */
    public void setReserveMins(int value) {
        this.reserveMins = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserID(String value) {
        this.userID = value;
    }

    /**
     * Gets the value of the apiUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApiUserId() {
        return apiUserId;
    }

    /**
     * Sets the value of the apiUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApiUserId(String value) {
        this.apiUserId = value;
    }

    /**
     * Gets the value of the createChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateChannel() {
        return createChannel;
    }

    /**
     * Sets the value of the createChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateChannel(String value) {
        this.createChannel = value;
    }

    /**
     * Gets the value of the isEpc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEpc() {
        return isEpc;
    }

    /**
     * Sets the value of the isEpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEpc(String value) {
        this.isEpc = value;
    }

}
