//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.02 at 05:15:32 PM CST 
//


package epc.epcsalesapi.soap.wsclient.createTmpReserve;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for invCreateTmpReserveResultBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invCreateTmpReserveResultBean"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="errMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="latestDeliveryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reserveLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="tmpReserveID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
//@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invCreateTmpReserveResultBean", propOrder = {
    "errMsg",
    "latestDeliveryDate",
    "reserveLocation",
    "result",
    "tmpReserveID"
})
public class InvCreateTmpReserveResultBean {

    protected String errMsg;
    protected String latestDeliveryDate;
    protected String reserveLocation;
    protected int result;
    protected int tmpReserveID;

    /**
     * Gets the value of the errMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * Sets the value of the errMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrMsg(String value) {
        this.errMsg = value;
    }

    /**
     * Gets the value of the latestDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatestDeliveryDate() {
        return latestDeliveryDate;
    }

    /**
     * Sets the value of the latestDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatestDeliveryDate(String value) {
        this.latestDeliveryDate = value;
    }

    /**
     * Gets the value of the reserveLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReserveLocation() {
        return reserveLocation;
    }

    /**
     * Sets the value of the reserveLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReserveLocation(String value) {
        this.reserveLocation = value;
    }

    /**
     * Gets the value of the result property.
     * 
     */
    public int getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     */
    public void setResult(int value) {
        this.result = value;
    }

    /**
     * Gets the value of the tmpReserveID property.
     * 
     */
    public int getTmpReserveID() {
        return tmpReserveID;
    }

    /**
     * Sets the value of the tmpReserveID property.
     * 
     */
    public void setTmpReserveID(int value) {
        this.tmpReserveID = value;
    }

}
