//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.02 at 05:15:32 PM CST 
//


package epc.epcsalesapi.soap.wsclient.createTmpReserve;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.smc.testSpringboot3ConsumeSoap.wsclient package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateTmpReserveEpc_QNAME = new QName("http://online_store.pos/", "CreateTmpReserveEpc");
    private final static QName _CreateTmpReserveEpcResponse_QNAME = new QName("http://online_store.pos/", "CreateTmpReserveEpcResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.smc.testSpringboot3ConsumeSoap.wsclient
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateTmpReserveEpc }
     * 
     */
    public CreateTmpReserveEpc createCreateTmpReserveEpc() {
        return new CreateTmpReserveEpc();
    }

    /**
     * Create an instance of {@link CreateTmpReserveEpcResponse }
     * 
     */
    public CreateTmpReserveEpcResponse createCreateTmpReserveEpcResponse() {
        return new CreateTmpReserveEpcResponse();
    }

    /**
     * Create an instance of {@link InvCreateTmpReserveBean }
     * 
     */
    public InvCreateTmpReserveBean createInvCreateTmpReserveBean() {
        return new InvCreateTmpReserveBean();
    }

    /**
     * Create an instance of {@link InvCreateTmpReserveResultBean }
     * 
     */
    public InvCreateTmpReserveResultBean createInvCreateTmpReserveResultBean() {
        return new InvCreateTmpReserveResultBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateTmpReserveEpc }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateTmpReserveEpc }{@code >}
     */
//    @XmlElementDecl(namespace = "http://online_store.pos/", name = "CreateTmpReserveEpc")
//    public JAXBElement<CreateTmpReserveEpc> createCreateTmpReserveEpc(CreateTmpReserveEpc value) {
//        return new JAXBElement<CreateTmpReserveEpc>(_CreateTmpReserveEpc_QNAME, CreateTmpReserveEpc.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateTmpReserveEpcResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateTmpReserveEpcResponse }{@code >}
     */
//    @XmlElementDecl(namespace = "http://online_store.pos/", name = "CreateTmpReserveEpcResponse")
//    public JAXBElement<CreateTmpReserveEpcResponse> createCreateTmpReserveEpcResponse(CreateTmpReserveEpcResponse value) {
//        return new JAXBElement<CreateTmpReserveEpcResponse>(_CreateTmpReserveEpcResponse_QNAME, CreateTmpReserveEpcResponse.class, null, value);
//    }

}
